### ISSUE TITLE
Make additional CIs also plugable

### ISSUE THREAD

**Issue by lukasburda** [jboss/tyr#100]
As there are interfaces for Commands and Checks implement also CIs.

**Comment by xstefank** [comment]
I don't suppose there will be a lot of new CIs emerging often. Is the effort worth it?

**Comment by lukasburda** [comment]
It was just an Idea. If it's not worth we could close this

**Comment by xstefank** [comment]
@lukasburda thanks for the idea but I don't think this is worth the effort.
