### ISSUE TITLE
Add check for the required number of commits in the PR

### ISSUE THREAD

**Issue by xstefank** [jboss/tyr#186]
Many projects require only one commit per PR. We should add a check that verifies user-defined number commit s per PR. This should also support a range regex if needed. So the config could look like this:

```
numberOfCommits: 1
```
or 
```
numberOfCommits: 1..5
```

**Comment by xvanick1** [comment]
> Many projects require only one commit per PR. We should add a check that verifies user-defined number commit s per PR. This should also support a range regex if needed. So the config could look like this:
> 
> ```
> numberOfCommits: 1
> ```
> 
> or
> 
> ```
> numberOfCommits: 1..5
> ```

Do you have any bounds for the maximum of commits?

**Comment by xstefank** [comment]
@xvanick1 not really, I think possitive `short` range should be enough. If not, we will change it later.
