### ISSUE TITLE
Retest command doesn't work properly with Quarkus

### ISSUE THREAD

**Issue by khermano** [jboss/tyr#84]
Debug shows that method TeamCityCI.triggerBuild(JsonObject prPayload) contains its information correctly (e.g. teamCityBranch is pull/35 etc.), but TeamCity is not receiving any information from posted json.
TeamCity recognizes that build was triggered and runs build under default branch (master), not predefined branch e.g. pull/35 with predefined information posted within json.

**Comment by xstefank** [comment]
I couldn't reproduce this. Everything works as expected on my machine.
